version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: travel_api_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: travel_api
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
